#!/bin/bash

# USE: create user messageId newMessage
curl  --request POST \
      --header "Content-Type: application/json" \
      --data "{\"userId\":\"${1}\", \"messageId\":\"${2}\", \"message\":\"${3}\" }" \
      --url  http://localhost:8080/api/v1/message

